### ISSUE TITLE
Question on default.yml

### ISSUE THREAD

**Issue by Joey-Xue** [largelymfs/deepcontact#2]
Hi I'm using deepcontact to generate some features. And I saw you are using Blast 2.2.6, which is a 2003 version. And I can't find a complete file of this version. The blast versions I can find don't contain the "makemat" function as required by the default.yml file. Hope you can help me with it. Thanks

**Comment by kad-ecoli** [comment]
ftp://ftp.ncbi.nlm.nih.gov/blast/executables/legacy.NOTSUPPORTED/2.2.26/

**Comment by Joey-Xue** [comment]
Thanks Kad! I will try
